---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-travis
    image: diodonfrost/ubuntu-16.04-ansible
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra